version: "3.8"

services:
  firebase_emulator:
    image: bjarkt/firebase_emulator
    build:  
      context: .
      dockerfile: Dockerfile.firebase
    ports:
      - "8080:8080" # firestore
      - "9099:9099" # auth
      - "4000:4000" # ui
      - "4400:4400" # emulator hub
      - "9150:9150" # ui websocket

  grafana_agent:
    image: grafana/agent:v0.39.2
    entrypoint:
      - /bin/grafana-agent
      - -server.http.address=0.0.0.0:12345
      - -config.file=/etc/agent/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      # - -enable-features=integrations-next
      - -config.expand-env
      # - -config.enable-read-api
    env_file: ./RecipesAPI.API/.env
    ports:
      - "4317:4317"
      - "12345:12345"
    volumes:
      - "./data/grafana-data:/etc/agent/data"
      - "./grafana/agent.yaml:/etc/agent/agent.yaml"

# configs:
#   firebasejson:
#     content: |
#       {
#         "emulators": {
#           "auth": {
#             "port": 9099,
#             "host": "0.0.0.0"
#           },
#           "functions": {
#             "port": 5001,
#             "host": "0.0.0.0"
#           },
#           "firestore": {
#             "port": 8080,
#             "host": "0.0.0.0"
#           },
#           "hosting": {
#             "port": 5000,
#             "host": "0.0.0.0"
#           },
#           "hub": {
#             "host": "0.0.0.0",
#             "port": 4400
#           },
#           "logging": {
#             "host": "0.0.0.0",
#             "port": 4500
#           },
#           "eventarc": {
#             "host": "0.0.0.0",
#             "port": 9299
#           },
#           "ui": {
#             "enabled": true,
#             "port": 4000,
#             "host": "0.0.0.0"
#           },
#         }
#       }