FROM node:alpine

RUN apk add openjdk11

RUN npm install -g firebase-tools

WORKDIR /app

COPY ./firebase.json ./firebase.json

CMD ["firebase", "--config", "firebase.json", "--project", "demo-recipesapi", "emulators:start", "--only", "firestore,auth"]
