# fly.toml file generated for recipesapi on 2023-01-04T18:12:35+01:00

app = "recipesapi-v2"
primary_region = "ams"

[env]
PORT = "8080"
ConnectionStrings__LocalData = "Data Source=/data/LocalData.db"
ConnectionStrings__SqliteCache = "Data Source=/data/SqliteCache.db"
FridaCsvPath = "/static-data/frida.csv"

[mounts]
source = "recipesapi_data"
destination = "/data"


[http_service]
internal_port = 8080
force_https = true
[http_service.concurrency]
soft_limit = 200
hard_limit = 250
type = "requests"

[checks]
[checks.http_healthcheck]
grace_period = "5s"
interval = "15s"
method = "get"
path = "/api/healthcheck/ready"
port = 8080
type = "http"
timeout = "5s"

[metrics]
port = 1234
path = "/metrics"
