server:
  log_level: debug

metrics:
  global:
    scrape_interval: 60s
    remote_write:
      - url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
        basic_auth:
          username: ${GRAFANA_CLOUD_PROM_USERNAME}
          password: ${GRAFANA_CLOUD_PASSWORD}
  configs:
    - name: default
      scrape_configs:
        - job_name: recipesapi
          static_configs:
            - targets: ["host.docker.internal:1234"]

traces:
  configs:
    - name: default
      receivers:
        otlp:
          protocols:
            grpc:
            # http:
        # jaeger:
        #   protocols:
        #     grpc:
      remote_write:
        - endpoint: tempo-eu-west-0.grafana.net:443
          basic_auth:
            username: ${GRAFANA_CLOUD_USERNAME}
            password: ${GRAFANA_CLOUD_PASSWORD}
      # batch:
      #   timeout: 15s
      #   send_batch_size: 1000
      #   send_batch_max_size: 2000
      batch:
        send_batch_size: 10000
        timeout: 5s
        send_batch_max_size: 0
