name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-restore --logger trx --results-directory "TestResults"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results
          path: TestResults
        if: ${{ always() }} # Always run this step, even if there are test failures

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: deploy
        id: deploy
        run: flyctl deploy --local-only
